version: '2'

services:
  sh:
    image: 'sh:latest'
    build:
      context: .
    container_name: sh
    ports:
      - "8081:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_HIKARI_CONNECTIONTIMEOUT=20000
      - SPRING_DATASOURCE_HIKARI_MAXIMUMPOOLSIZE=5
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/compose-postgres
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create
      - SPRING_JPA_GENERATE_DDL=true
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQL94Dialect
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_SESSION_STORE_TYPE=none
  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    ports:
      - "5433:5432"
    volumes:
      - sh_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres
volumes:
  sh_data: